version: '3.1'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: telemedicine
      POSTGRES_PASSWORD: root
  app:
    depends_on: [ db ]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_USERNAME: admin
        DB_PASSWORD: root